name: React CI/CD Pipeline

on:
  workflow_call:
    inputs:
      node-version:
        required: false
        type: string
        default: '20'
      project-key:
        required: true
        type: string
      project-name:
        required: true
        type: string
      enable-webhook:
        required: false
        type: boolean
        default: false
    secrets:
      SONAR_TOKEN:
        required: true
      SONAR_HOST_URL:
        required: true
      WEBHOOK_URL:
        required: false
      WEBHOOK_SECRET:
        required: false

jobs:
  sonar-analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        with:
          projectBaseDir: .
          args: >-
            -Dsonar.projectKey=${{ inputs.project-key }}
            -Dsonar.projectName=${{ inputs.project-name }}
            -Dsonar.language=javascript
            -Dsonar.sources=src

  notify-completion:
    needs: sonar-analysis
    if: ${{ always() && inputs.enable-webhook }}
    uses: ./.github/workflows/webhook-run.yml
    with:
      webhook-type: "sonar-completed"
      project-key: ${{ inputs.project-key }}
      additional-data: '{"pipeline_type": "react", "node_version": "${{ inputs.node-version }}"}'
    secrets:
      WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
      WEBHOOK_SECRET: ${{ secrets.WEBHOOK_SECRET }}