# .github/workflows/react-run.yml in ci-cd-template
name: React CI with SonarCloud

on:
  workflow_call:
    inputs:
      repo_name:
        required: true
        type: string

jobs:
  build-sonar:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout candidate repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci || yarn install --frozen-lockfile

      - name: Build
        run: npm run build || yarn build

      - name: Ensure SonarCloud project exists
        run: |
          SONAR_PROJECT_KEY=talentis-io_${{ inputs.repo_name }}
          SONAR_ORG=talentis-io
          RESPONSE=$(curl -s -u ${{ secrets.SONAR_TOKEN }}: \
            "https://sonarcloud.io/api/projects/search?projects=$SONAR_PROJECT_KEY")
          if ! echo "$RESPONSE" | grep -q "\"key\":\"$SONAR_PROJECT_KEY\""; then
            curl -s -u ${{ secrets.SONAR_TOKEN }}: -X POST \
              "https://sonarcloud.io/api/projects/create" \
              -d "project=$SONAR_PROJECT_KEY" \
              -d "organization=$SONAR_ORG" \
              -d "name=${{ inputs.repo_name }}"
            sleep 5
          fi

      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v5.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=talentis-io_${{ inputs.repo_name }}
            -Dsonar.organization=talentis-io
            -Dsonar.host.url=https://sonarcloud.io
            -Dsonar.branch.name=master

