name: React CI/CD Pipeline

on:
  workflow_call:
    inputs:
      node-version:
        required: false
        type: string
        default: '20'
      project-key:
        required: true
        type: string
      project-name:
        required: true
        type: string
      enable-webhook:
        required: false
        type: boolean
        default: false
    secrets:
      SONAR_TOKEN:
        required: true
      SONAR_HOST_URL:
        required: true
      WEBHOOK_URL:
        required: false
      WEBHOOK_SECRET:
        required: false

jobs:
  sonar-analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for accurate analysis

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        with:
          projectBaseDir: .
          args: >
            -Dsonar.projectKey=${{ inputs.project-key }}
            -Dsonar.projectName=${{ inputs.project-name }}
            -Dsonar.language=javascript
            -Dsonar.sources=src
            -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }}
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}
            -Dsonar.scm.provider=git
            -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info