# .github/workflows/react-run.yml in ci-cd-template
name: React CI with SonarCloud

on:
  workflow_call:
    inputs:
      repo_name:
        required: true
        type: string

jobs:
  build-sonar:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout candidate repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci || yarn install --frozen-lockfile

      - name: Build
        run: npm run build || yarn build

      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v5.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=talentis-io_${{ inputs.repo_name }}
            -Dsonar.organization=talentis-io
            -Dsonar.host.url=https://sonarcloud.io
