name: React CI Pipeline

on:
  workflow_call:
    inputs:
      repo_name:
        required: true
        type: string
      branch_name:
        required: true
        type: string

jobs:
  build-react:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci || yarn install --frozen-lockfile

      - name: Build project
        run: npm run build || yarn build

  sonar:
    needs: build-react
    uses: talentis-io/ci-cd-templates/.github/workflows/sonar-run.yml@master
    with:
      repo_name: ${{ inputs.repo_name }}
      branch_name: ${{ inputs.branch_name }}
      build_command: "npm run build"
      sonar_sources: "src"
      sonar_exclusions: "**/node_modules/**,**/build/**"
    secrets: inherit

  notify:
    needs: sonar
    uses: talentis-io/ci-cd-templates/.github/workflows/webhook-run.yml@master
    with:
      repo_name: ${{ inputs.repo_name }}
      branch_name: ${{ inputs.branch_name }}
    secrets: inherit
